### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by nitrag** [jim-rhoades/DivingBoard#2]
Hey Jim, great contribution here! Thanks.

I'd like to make a suggestion. I don't believe the Storyboard/Segues to `PhotoCollectionViewController` are necessary to only house `PhotoCollectionViewCell`. I think it would be much easier to read the code if created programmatically. 

What do you think?

**Comment by jim-rhoades** [comment]
I just released version 1.1 with some big changes to the interface. The Storyboard is still there, but there's no reason to remove it. As part of the UI changes, there are no more child view controllers... so both the Storyboard and code have been simplified.

I think this release will fit better with how you wanted to use it, since it shows the search bar right away. Also, you can now present it by pushing it onto a UINavigationController stack (in addition to the existing ways of presenting it modally):

```swift
let unsplashPicker = DivingBoard.unsplashPicker(withClientID: unsplashAppID,
                                                        presentingViewController: self)
unsplashPicker.hidesBottomBarWhenPushed = true // only needed if your app is showing a toolbar like PhotoViewer does
navigationController?.pushViewController(unsplashPicker, animated: true)
```
